#!/bin/bash
SCRIPT_DIR=(`dirname "$0"`)
DST_DIR=(`realpath $4`)

cd $CI_PROJECT_DIR

# cleanup any tmp generated by tests
rm -rf ./tmp*
rm -rf $DST_DIR

# create dir where we will put bin files
mkdir $DST_DIR
tests_list=(`ls ./tests/*.ispc`)

for test in "${tests_list[@]}"
do
   test_name=`basename $test`
   # generate bin
   set -e
   ./run_tests.py -a $1 -t $2 --save-bin $test --ispc_output=$3 --test_time 20
   set +e
   base_test_name=`basename $test | cut -d"." -f1`
   case $2 in
   'gen9-x8')
     test_postfix=".simd8.spv"
     ;;
   'gen9-x16')
     test_postfix=".simd16.spv"
     ;;
   esac
   test_name=$base_test_name$test_postfix
   mkdir $DST_DIR/$test_name
   mv tmp*/* $DST_DIR/$test_name
   rm -rf tmp*

   # remove empty directory and skip this test
   if [ -z "$(ls -A $DST_DIR/$test_name)" ]; then
        rm -rf $DST_DIR/$test_name
        continue
   fi

   # check if skip on some gpus
   cat $test | grep "skip on cpu=tgllp" && echo "1" > $DST_DIR/$test_name/tgllp.skip
   cat $test | grep "skip on cpu=tgllp" && echo "1" > $DST_DIR/$test_name/dg1.skip
   cat $test | grep "skip on cpu=dg2" && echo "1" > $DST_DIR/$test_name/dg2.skip
done

set -e
cd $DST_DIR
# remove empty dirs
#find . -type d -empty -delete
# copy run_test.py to each test dir
find . -type d -print | xargs -n 1 cp -v $SCRIPT_DIR/run_test.py

yaml_file=tests.yaml
#generate yaml file
for test_dir in ./*.spv/ ;
do
    test_name=`basename $test_dir`
    echo "- fail: []" >> $yaml_file
    echo "  labels: []" >> $yaml_file
    echo "  platforms: [kbl, tgllp, dg1]" >> $yaml_file
    echo "  runtime: l0" >> $yaml_file
    echo "  test: $test_name" >> $yaml_file
    echo "  version: 1" >> $yaml_file
    echo "" >> $yaml_file
done

#run created tests
for test_dir in ./*.spv/ ; do (cd "$test_dir" && echo "Running $test_dir..." && python3 ./run_test.py || echo "$test_dir FAILED"); done
